version: "3.9"
services:
  postgres:
    image: "postgres:latest"
    build: ./postgres_app
    env_file: ./postgres_app/postgres.env
    ports:
      - 15432:5432
    volumes:
      - ./postgres_app/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - custom
    container_name: postgres_app

  transactions:
    image: "golang:latest"
    build: ./transactions_app
    ports:
      - 8080:8080
    volumes:
    - type: bind
      source: ./transactions_app/src
      target: /src
    networks:
      - custom
    container_name: transactions_app

networks:
  custom: